`@InjectResources` fluid Java DSL helps to load and parse the resources conveniently.

=== Dependency

Add `inject-resources-core` dependency to your project.

Using Maven:

[source, xml, subs="+attributes"]
----
<dependency>
    <groupId>io.hosuaby</groupId>
    <artifactId>inject-resources-core</artifactId>
    <version>{project-version}</version>
</dependency>
----

Or using Gradle:

[source, groovy, subs="+attributes"]
----
compile group: 'io.hosuaby', name: 'inject-resources-core', version: '{project-version}'
----

=== Java DSL example

[source, java]
----
var text = resource()
        .withPath("/io/hosuaby/junit/jupiter", "resource.txt")
        .text();
----

==== Entry point

Method `InjectResources#resource` is an entry point of Java DSL. It's recommended to import this method statically:

[source, java]
----
import static io.hosuaby.inject.resources.core.InjectResources.resource;
----

==== Choosing the classloader

To choose a classloader used to load a single resource it's possible to use `resource().onClassLoader(classLoader)` or
`resource().onClassLoaderOf(clazz)`.

Example:

[source, java]
----
var text = resource()
        .onClassLoader(this.getClass().getClassLoader())
        .withPath("/io/hosuaby/junit/jupiter", "resource.txt")
        .text();

// or

var text = resource()
        .onClassLoaderOf(this.getClass())
        .withPath("/io/hosuaby/junit/jupiter", "resource.txt")
        .text();
----

We can omit the choice of a classloader with `resource().withPath(path)`. In that case the context classloader
`Thread.currentThread().getContextClassLoader()` is used.

==== Specifying path to resource

Method `withPath(path)` allows to define the path to the requested resource. The next three notations are equivalents:

[source, java]
----
// There notations are equivalent
resource().withPath("/io/hosuaby/junit/jupiter/resource.txt");
resource().withPath("/io/hosuaby/junit/jupiter", "resource.txt");
resource().withPath("io", "hosuaby", "junit", "jupiter", "resource.txt");
----

==== Read text content

Content of a text resource can be read as `String` using method `text()`:

[source, java]
----
var text = resource().withPath("resource.txt").text();

// or with specified charset
var text = resource().withPath("resource.txt").text(StandardCharsets.UTF_8);
----

==== Read binary content

Content of a binary resource can be read as `byte[]` using method `bytes()`:

[source, java]
----
var fibonacci = resource().withPath("fibonacci.bin").bytes();
----

==== Parsing of resource content

In order to parse resources content, need to get one of provided wrappers around that resource. Wrapper can be obtained by calling one of the those methods:

- `asInputStream()` - returns wrapper around resource represented as an `InputStream`.
- `asByteArray()` - resource as bytes array.
- `asReader()` - resource as `Reader`. Can also be `asReader(Charset charset)`.
- `asLines()` - resource as a stream of text lines. Can also be `asLines(Charset charset)`.
- `asText()` - resource as text. Can also be `asText(Charset charset)`.

Those wrappers (except those returned by `asLines()`) expose four methods that can be used to process content of a resource:

- `parse(Function<I, O> parsingFunction)` - parses content of resource using `parsingFunction`.
- `parseChecked(ThrowingFunction<I, O> parsingFunction)` - parses content of resource using `parsingFunction` that may
  throw exception.
- `then(Consumer<I> contentConsumer)` - processes content of resource using `contentConsumer`.
- `thenChecked(ThrowingConsumer<I> contentConsumer)` - processes content of resource using `contentConsumer` that may
  throw exception.

===== Ignoring uncaught exceptions

Two new functional interfaces are provided by the library: `ThrowingFunction` and `ThrowingConsumer`. They are similar to
interfaces `Function` and `Consumer` from `java.util.function` but they are able to capture lambdas that may throw a
checked exception. Example:

[source, java]
----
// Instead of this
var dbConnection = resource()
        .withPath("db.properties")
        .asInputStream()
        .parse(inputStream -> {
            try {
                return reader.readValue(inputStream);
            } catch (IOException parsingException) {
                throw new RuntimeException(parsingException);
            }
        });

// We can write this
var dbConnection = resource()
        .withPath("db.properties")
        .asInputStream()
        .parseChecked(reader::readValue);
----

===== Read resource line by line

The resource wrapper returned by method `asLines()` able to process text resource file line by line. It's practical to parse
resources in line based formats, like CSV. Example:

[source, java]
----
var header = new AtomicReference<String>();
var lines = new ArrayList<String>();

resource()
        .withPath("cities.csv")
        .asLines()
        .onFirstLine(header::set)
        .forEachLine(lines::add);
----
