[[inject-resources]]
= @InjectResources usage guide
:toc: left
:toclevels: 4
:numbered:
:icons: font
:hide-uri-scheme:
:source-highlighter: prettify
Alexei Klenin

(C) 2020 - 2022 by Alexei Klenin

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any
fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or
electronically.

== Preface

`@InjectResources` is a Java library providing simple and convenient way to load and parse resource files. It does all
opening and closing of input streams and handles exceptions.

Java 8+ is required in order to use this library.

== Repository

Artifacts belonging to `@InjectResources` are hosted on _JCenter_ so you need to set it up as a repository in your
_Maven/Gradle_ project.

For Maven:

[source, xml]
----
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>https://jcenter.bintray.com</url>
    </repository>
</repositories>
----

For Gradle:

[source, groovy]
----
repositories {
    jcenter()
}
----

== Modules

Library composed of following modules:

- <<inject-resources-core>>
- <<inject-resources-spring>>
- <<inject-resources-junit-jupiter>>
- <<inject-resources-junit-vintage>>

[[inject-resources-core]]
== Java DSL

include::inject-resources-core/index.adoc[]

[[inject-resources-spring]]
== Spring module

include::inject-resources-spring/index.adoc[]

[[inject-resources-junit-jupiter]]
== JUnit Jupiter extension

include::inject-resources-junit-jupiter/index.adoc[]

[[inject-resources-junit-vintage]]
== JUnit 4 (Vintage) extension

include::inject-resources-junit-vintage/index.adoc[]
