`@InjectResources` JUnit Jupiter extension gives ability to inject content of resources into JUnit5 tests.

=== Dependency

Add `inject-resources-junit-jupiter` dependency to your project.

Using Maven:

[source, xml, subs="+attributes"]
----
<dependency>
    <groupId>io.hosuaby</groupId>
    <artifactId>inject-resources-junit-jupiter</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

Or using Gradle:

[source, groovy, subs="+attributes"]
----
testCompile group: 'io.hosuaby', name: 'inject-resources-junit-jupiter', version: '{project-version}'
----

=== Test extension

In order to use this plugin, we need to add extension to the test class:

[source, java]
----
@TestWithResources  // add JUnit Jupiter extension
class InjectResourcesTests {
}
----

=== Resource content injection

To inject content of resource files in our tests we need to use one of the `@Given*` annotations (called *resource
annotations*). Resource annotations can be placed on `static` class fields, instance fields and parameters of test
methods. Injected fields must be non-private and non-final.

[source, java]
----
@TestWithResources
class InjectResourcesTests {

    @GivenTextResource("/com/adelean/junit/jupiter/resource.txt") <1>
    static String classField;

    @GivenTextResource("/com/adelean/junit/jupiter/resource.txt") <2>
    String instanceField;

    @Test
    public void testWithResources(
            @GivenTextResource("/com/adelean/junit/jupiter/resource.txt") <3>
            String testParameter) {
    }
}
----
<1> Inject into static class field
<2> Inject into instance field
<3> Inject into test parameter

=== Load binary resource

Given a resource `/com/adelean/junit/jupiter/fibonacci.bin` with binary content:

[source, text]
----
1 1 2 3 5 8 13 21 34 55 89
----

Inject the content of that resource using annotation `@GivenBinaryResource`:

[source, java]
----
@TestWithResources
class InjectBinaryResourcesTests {

    @GivenBinaryResource("/com/adelean/junit/jupiter/fibonacci.bin")
    byte[] fibonacci;

    @Test
    public void testInjectBinaryContentIntoByteArrayInstanceField() {
        assertThat(fibonacci)
                .contains(1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89);
    }
}
----

=== Load text resource

Assuming there is a resource `/com/adelean/junit/jupiter/resource.txt` containing

[source, text]
----
The quick brown fox jumps over the lazy dog.
----

Content of that resource can be injected into test using annotation `@GivenTextResource`:

[source, java]
----
@TestWithResources
class InjectTextResourcesTests {

    @GivenTextResource("/com/adelean/junit/jupiter/resource.txt")
    String instanceField;

    @Test
    public void testInjectTextIntoStringInstanceField() {
        assertThat(instanceField)
                .isEqualTo("The quick brown fox jumps over the lazy dog.");
    }
}
----

=== Load properties resources

Given a properties resource `/com/adelean/junit/jupiter/db.properties` with content:

[source, properties]
----
db.user=hosuaby
db.password=password
db.url=localhost
----

These properties can be injected into tests using annotation `@GivenPropertiesResource`:

[source, java]
----
@TestWithResources
class InjectPropertiesResourcesTests {

    @GivenPropertiesResource("/com/adelean/junit/jupiter/db.properties")
    Properties dbProperties;

    @Test
    public void testInjectTextIntoStringInstanceField() {
        assertThat(dbProperties)
                .containsEntry("db.user", "hosuaby")
                .containsEntry("db.password", "password")
                .containsEntry("db.url", "localhost");
    }
}
----

=== Load and parse JSON

This library simplifies loading and parsing of _JSON_ & _JSONL_ (JSON Lines) files. Native support for
https://github.com/FasterXML/jackson[Jackson] and https://github.com/google/gson/blob/master/UserGuide.md[GSON]
gives ability to parse _JSON_ content into `Map<String, Object>`, `JsonNode` (for _Jackson_) & `JsonElement`
(for _GSON_) or to Java POJO.

Use annotation `@GivenJsonResource` for _JSON_ and `@GivenJsonLinesResource` for _JSONL_.

In order to parse _JSON/JSONL_ we need to declare a parser. Parsers are fields or functions that are annotated with
`@With*` annotations.

[source, java]
----
/* Jackson */
@WithJacksonMapper
ObjectMapper objectMapper = new ObjectMapper();

/* or GSON */
@WithGson
Gson gson = new Gson();
----

Following subsections explain how to parse _JSON/JSONL_ with _Jackson_ or _GSON_ in detail.

==== Jackson

In order to parse resources with _Jackson_ both `jackson-core` & `jackson-databind` must be present on the Classpath.

To specify which `ObjectMapper` is used to parse _JSON_ use annotation `@WithJacksonMapper`:

[source, java]
----
@WithJacksonMapper
ObjectMapper objectMapper = new ObjectMapper();
----

Configure your parser as you need:

[source, java]
----
@WithJacksonMapper
ObjectMapper objectMapper = new ObjectMapper()
        .registerModule(new JavaTimeModule());
----

Now you can inject content of _JSON/JSONL_ into your tests:

[source, java]
----
@TestWithResources
class TestsWithJackson {

    @WithJacksonMapper
    ObjectMapper objectMapper = new ObjectMapper()
            .registerModule(new JavaTimeModule());

    /* JSON */
    @GivenJsonResource("/com/adelean/junit/jupiter/sponge-bob.json")
    Map<String, Object> jsonAsMap;

    @GivenJsonResource("/com/adelean/junit/jupiter/sponge-bob.json")
    JsonNode jsonNode;

    @GivenJsonResource("/com/adelean/junit/jupiter/sponge-bob.json")
    Person spongeBob;

    /* JSONL */
    @GivenJsonLinesResource("/com/adelean/junit/jupiter/logs.jsonl")
    Log[] logsAsArray;

    @GivenJsonLinesResource("/com/adelean/junit/jupiter/logs.jsonl")
    Collection<Log> logsAsCollection;
}
----

==== GSON

To parse _JSON/JSONL_ resources with _GSON_, `com.google.code.gson:gson` must be present on Classpath.

Declare _GSON_ object used to parse resources and annotate it with `@WithGson`:

[source, java]
----
@WithGson
Gson gson = new Gson();
----

Now you can inject content of _JSON/JSONL_ into your tests:

[source, java]
----
@TestWithResources
class TestsWithGson {

    @WithGson
    Gson gson = new GsonBuilder();

    /* JSON */
    @GivenJsonResource("/com/adelean/junit/jupiter/sponge-bob.json")
    Map<String, Object> jsonAsMap;

    @GivenJsonResource("/com/adelean/junit/jupiter/sponge-bob.json")
    JsonElement jsonElement;

    @GivenJsonResource("/com/adelean/junit/jupiter/sponge-bob.json")
    Person spongeBob;

    /* JSONL */
    @GivenJsonLinesResource("/com/adelean/junit/jupiter/logs.jsonl")
    Log[] logsAsArray;

    @GivenJsonLinesResource("/com/adelean/junit/jupiter/logs.jsonl")
    Collection<Log> logsAsCollection;
}
----

=== Load and parse YAML

Thanks to native support of https://bitbucket.org/asomov/snakeyaml/wiki/Documentation[Snakeyaml] library is able to
parse _YAML_ resources files. `org.yaml:snakeyaml` must be present on Classpath in order to use that feature.

Declare `Yaml` object used for parsing and annotate it with `@WithSnakeYaml`:

[source, java]
----
@WithSnakeYaml
Yaml yaml = new Yaml();
----

Resource annotations `@GivenYamlResource` and `@GivenYamlDocumentsResource` can be now used to parse _YAML_ with single
or multiple documents respectively:

[source, java]
----
@TestWithResources
class TestsWithYaml {

    @WithSnakeYaml
    Yaml yaml = new Yaml();

    /* YAML resource with a single document */
    @GivenYamlResource("/com/adelean/junit/jupiter/receipt.yml")
    Map<String, Object> receipt;

    @GivenYamlResource("/com/adelean/junit/jupiter/sponge-bob.yaml")
    Person spongeBob;

    /* YAML resource with multiple documents separated by '---' */
    @GivenYamlDocumentsResource("/com/adelean/junit/jupiter/stacktrace.yaml")
    List<Map<String, Object>> stacktraceAsList;
}
----

`Yaml` object must be configured to be able to parse documents from multi-document _YAML_ into POJO:

[source, java]
----
@TestWithResources
class TestsWithYaml {

    /* Assuming we have defined class Log */
    @WithSnakeYaml("log-parser")
    Yaml logParser = new Yaml(new Constructor(Log.class));

    @GivenYamlDocumentsResource(from = "/com/adelean/junit/jupiter/logs.yml", yaml = "log-parser")
    Log[] logsAsArray;
}
----

=== Parsers

This section talks about objects annotated with `@With*` annotations. Those objects are called *parsers*. Annotations
`@With*` are called *parser annotations*. They can annotate class and instance fields or methods of test classes.

[source, java]
----
// Parser object from field
@WithJacksonMapper
ObjectMapper objectMapper = new ObjectMapper();

// Parser object from function
@WithJacksonMapper("custom-mapper")
ObjectMapper objectMapper() {
    return new ObjectMapper().registerModule(new JavaTimeModule());
}
----

Parsers can be *named* or *anonymous*. Named parsers are useful when some resources require a special configuration of
parser.

In following example, resource `/com/adelean/junit/jupiter/logs.jsonl` is parsed by `ObjectMapper` named
_"custom-mapper"_.

[source, java]
----
@TestWithResources
class TestsWithNamedParser {

    // Named parser
    @WithJacksonMapper("custom-mapper")
    ObjectMapper objectMapper = new ObjectMapper()
            .registerModule(new JavaTimeModule());

    // JSONL resource parser by parser named 'custom-mapper'
    @GivenJsonLinesResource(
        from = "/com/adelean/junit/jupiter/logs.jsonl",
        jacksonMapper = "custom-mapper")
    Collection<Log> logsAsCollection;
}
----

==== Parser scopes

By default, parsers are scoped to test class where they were defined. If a test class inherits from another class,
parsers defined in superclass can be used in subclass:

[source, java]
----
abstract class SuperClassWithParser {

    @WithJacksonMapper("custom-mapper")
    ObjectMapper objectMapper = new ObjectMapper()
            .registerModule(new JavaTimeModule());
}

@TestWithResources
class TestsSubclass extends SuperClassWithParser {

    @GivenJsonLinesResource(
        from = "/com/adelean/junit/jupiter/logs.jsonl",
        jacksonMapper = "custom-mapper")
    Collection<Log> logsAsCollection;
}
----

==== Tests advice

It is possible to define a parser that can be used by all tests on the Classpath by creating a `public` `final` class
annotated with `@TestsAdvice`:

[source, java]
----
@TestsAdvice
public final class GlobalJacksonMapper {

    @WithJacksonMapper("custom-mapper")
    ObjectMapper objectMapper() {
        return new ObjectMapper().registerModule(new JavaTimeModule());
    }
}

@TestWithResources
class TestsWithJson {

    @GivenJsonLinesResource(
        from = "/com/adelean/junit/jupiter/logs.jsonl",
        jacksonMapper = "custom-mapper")
    Collection<Log> logsAsCollection;
}
----
